# Generated by Django 5.2.4 on 2025-07-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author_names', models.CharField(max_length=255)),
                ('average_rating', models.FloatField()),
                ('ratings_count', models.IntegerField()),
                ('num_pages', models.IntegerField(blank=True, null=True)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('genre_1', models.CharField(blank=True, max_length=100, null=True)),
                ('genre_2', models.CharField(blank=True, max_length=100, null=True)),
                ('genre_3', models.CharField(blank=True, max_length=100, null=True)),
                ('genre_4', models.CharField(blank=True, max_length=100, null=True)),
                ('genre_5', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
